name: Deploy website

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build static files

    steps:

    - name: checkout branch
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: 0
        submodules: true

    - name: install build deps
      run: make install

    - name: hugo build
      run: make build

    - name: Archive static build
      uses: actions/upload-artifact@v4
      with:
        name: static-build
        path: build/
        retention-days: 7


  deploy:
    runs-on: ubuntu-latest
    name: Deploy to FTP server
    needs: build

    steps:

    - name: checkout branch
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: 0
        submodules: true

    - name: Download static build
      uses: actions/download-artifact@v4
      with:
        name: static-build
        path: build

    - name: install lftp
      run: echo "set man-db/auto-update false" | sudo debconf-communicate && sudo dpkg-reconfigure man-db && sudo apt-get install -y lftp

    - name: mirror local build/ with remote www/
      run: bash rsync_ftp.bash ${{ secrets.FTP_USER }} ${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} ./build /www 4
