name: 🚀 Deploy Website

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: 🛠️ Build and Deploy Website
    container: hugomods/hugo:latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensure Hugo themes are checked out if they are submodules

      - name: 🏗️ Build Static Site with Hugo
        run: hugo --minify

      - name: 🚀 Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./public/
          server-dir: /www/
